#!/bin/bash

set -e
set -x

echo
echo "===> Build started at $(date)"
echo
START=$SECONDS

# Unconditionally print elapsed build time at exit
function finish {
  echo "===> Elapsed time: $(($SECONDS - $START)) seconds"
}
trap finish EXIT

echo "---> Preparing source..."
mkdir -p $SOURCE/github.com/dhlparcel/flow-address-service

cp -Rf /tmp/src/. $SOURCE/github.com/dhlparcel/flow-address-service

cd $SOURCE/github.com/dhlparcel/flow-address-service/address-service

echo "---> Downloading dependencies..."
#go get -v ./...

echo "---> Building application source..."
#cd $GO_BUILD_DIR

make
#go build -v -o main
#go install main
mkdir -p $GOPATH/bin
mv address-service $GOPATH/bin

cd ../address-service-ui
sed -i 's/runningInProduction = false/runningInProduction = true/' app/environment.ts
npm install
typings install
npm run tsc
rm -rf address-ui-dist && mkdir address-ui-dist
cp index.html styles.css systemjs.config.js address-ui-dist/
cp -r node_modules address-ui-dist/
cp -r app address-ui-dist/
cp -r images address-ui-dist/
cd address-ui-dist/app && find . -name "*.ts" | xargs rm
mv address-ui-dist $GOPATH/bin

echo
echo "===> Build completed at $(date)"

# Fix source directory permissions
fix-permissions ./
fix-permissions $GOPATH/bin
